### PR TITLE
Correct the Scanlist Bug

### PR DESCRIPTION
**Pull request by g4eml**
Correct the scanlist bug where channels above 256 are incorrectly entered in the scanlist.  Not yet fully tested but it does appear to work.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Excellent...

Thanks. I'll merge and rebuild.

BTW. Think I'll do a release build and put the binaries on github to make things more accessible to the wider Amateur radio community.

**Comment by g4eml** [comment]
Hi Roger, 

One thing I noticed was that the current build does not include the file ‘Tones.txt’ and it complains it is missing when you try to view a channel.  Manually copying the file from the genuine CPS folder gets it going but it really needs adding to the project. 

73 

Colin.

**Comment by lxa520** [comment]
new version revise this bug; the contatct of channel , if it over 256, donot save bug

**Comment by rogerclarkmelbourne** [comment]
I checked the latest code and the fix for this is still in place

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/master/DMR/NormalScanForm.cs#L859

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/development/DMR/NormalScanForm.cs#L859


Please clarify where this bug occurs,  as this issue is for the Scan form

If you have an issue on some other form , it may be a different issue

**Comment by rogerclarkmelbourne** [comment]
@lxa520 

Are you @lion ?

**Comment by lxa520** [comment]
Yes i am lion; i am form china

**Comment by rogerclarkmelbourne** [comment]
OK.

I thought it was too much of a co-incidence...

Please can you explain this bug in more detail, and also can you raise and issue for the other bug you mentioned.

My current priority is to bug fix the existing bugs that can be fixed in the CPS (some bugs are in the firmware so I can't fix those at the moment)
Then next priority is to prepare for changes in CPS 3.1.x (Rx Group list changes) etc

**Pull request merged**
