### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by SQ9MDD**
The first attempt to translate.
Today XML only.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Fantastic...

Thanks.

XML only is fine. No one has translated the CHM to any other languages.
The German.chm has English in it

**Comment by rogerclarkmelbourne** [comment]
Oops.
Sorry. Pressed the wrong button.

I"m merging now...

**Comment by SQ9MDD** [comment]
I'm working with CHM file now...

**Comment by rogerclarkmelbourne** [comment]
OK. Can you let me know how you decompile and recompile a CHM so perhaps @dg9vh  can translate the help into German, (as well as the XML)

I will need to update the installer script to add the new files and then run the installer script to build a new exe. But its getting too late to do that today, as its 22:15 local time

But I will do it first thing tomorrow morning

**Comment by SQ9MDD** [comment]
Decompile is easy just unpack *.chm file with 7zip or better you can use Microsoft HTML HELP WORKSHOP.
Just uploaded decompiled english.chm to my github for easy translation

**Comment by SQ9MDD** [comment]
HTML Help Workshop ->
https://www.microsoft.com/en-us/download/details.aspx?id=21138

**Comment by rogerclarkmelbourne** [comment]
@SQ9MDD 

Did you say that some text would not fit and the "labels" needed to be made wider (in the programming) ?

I have published a new dev version exe

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/raw/development/installer/RadioddityCPS2.0.5CommunityEditionInstaller.exe

Can you test and also let me know which text labels (or possibly ComboBox - menus etc ) are not wide enough for the Polish language version

**Pull request merged**
